<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Not now</name>
   <tag></tag>
   <elementGuidId>81de7be0-cf1b-4c3b-9b5e-0c11dcf32003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ap-account-fixup-phone-skip-link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ap-account-fixup-phone-skip-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14115886-7f14-4c37-a273-1bbf3ce3c8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ap-account-fixup-phone-skip-link</value>
      <webElementGuid>68569492-a450-45a1-a0cb-f72efc38bb25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-normal</value>
      <webElementGuid>7f464f19-fadf-48b8-9426-194f3621ae56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.com/ap/signin?openid.pape.max_auth_age=900&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;appActionToken=zTyBv5j2Bc7KqhT0bllFj2BGTySOcRIj3D&amp;pageId=usflex&amp;openid.pape.preferred_auth_policies=http%3A%2F%2Fschemas.openid.net%2Fpape%2Fpolicies%2F2007%2F06%2Fnone&amp;openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3Fref_%3Dnav_custrec_signin%26returnFromLogin%3D1&amp;openid.assoc_handle=usflex&amp;partialToken=PT%7C1%7C0I1P7oBYDg0N0YFk81K6qp8gGH8INH7Q436iAkfOIWgstUFVvAkg9zz3bdb1Mi3OBVQT06yNUHxe0NV6txZ25IQjZNKlsiBKuzrBlGvfGBz9zwLUeaemSzqnKVEiLiddkblNiyBy7wz+5jz93LQFd9I8EBZCnKoMrHYx1mjNR721CZYtSQyjSJ2v%2FbeIMneta5CJTlMty+wKWRZyl%2Fj2X8OI61l03L99UkqlBVdUzgGBdjNJe6OycAD+mEms3ZDSu2XiKr2jQT%2F6NE%2FzPAD2C0Wr%2F5IeKafvQwjBjOpuBCu5uAc51XWZsCV1TkHIsXz5yiD5aU9Kf8rcs1hAERO03A%3D%3D&amp;openid.mode=checkid_setup&amp;appAction=ACCOUNT_FIXUP_PHONE_ADD_COMPLETE&amp;ref_=ap_reachability_skip&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;authenticationPolicy=SinglefactorWithMobileVerification</value>
      <webElementGuid>4369c07b-8ad3-4908-8eb9-84335c3b6baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Not now
                </value>
      <webElementGuid>8da90338-e704-417d-9eec-899a6926fa38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ap-account-fixup-phone-skip-link&quot;)</value>
      <webElementGuid>75b550a7-5832-48d0-8f08-2310967c51b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ap-account-fixup-phone-skip-link']</value>
      <webElementGuid>c3f43e01-f9f9-402d-b15a-554ddbf5823b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='auth-account-fixup-phone-form']/div/div[5]/div/a</value>
      <webElementGuid>405821ab-6dd6-4a3e-8bbd-22f2eb595fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Not now')]</value>
      <webElementGuid>4d5fdad1-eb1f-491d-ae59-cc98e3b00e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.com/ap/signin?openid.pape.max_auth_age=900&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;appActionToken=zTyBv5j2Bc7KqhT0bllFj2BGTySOcRIj3D&amp;pageId=usflex&amp;openid.pape.preferred_auth_policies=http%3A%2F%2Fschemas.openid.net%2Fpape%2Fpolicies%2F2007%2F06%2Fnone&amp;openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3Fref_%3Dnav_custrec_signin%26returnFromLogin%3D1&amp;openid.assoc_handle=usflex&amp;partialToken=PT%7C1%7C0I1P7oBYDg0N0YFk81K6qp8gGH8INH7Q436iAkfOIWgstUFVvAkg9zz3bdb1Mi3OBVQT06yNUHxe0NV6txZ25IQjZNKlsiBKuzrBlGvfGBz9zwLUeaemSzqnKVEiLiddkblNiyBy7wz+5jz93LQFd9I8EBZCnKoMrHYx1mjNR721CZYtSQyjSJ2v%2FbeIMneta5CJTlMty+wKWRZyl%2Fj2X8OI61l03L99UkqlBVdUzgGBdjNJe6OycAD+mEms3ZDSu2XiKr2jQT%2F6NE%2FzPAD2C0Wr%2F5IeKafvQwjBjOpuBCu5uAc51XWZsCV1TkHIsXz5yiD5aU9Kf8rcs1hAERO03A%3D%3D&amp;openid.mode=checkid_setup&amp;appAction=ACCOUNT_FIXUP_PHONE_ADD_COMPLETE&amp;ref_=ap_reachability_skip&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;authenticationPolicy=SinglefactorWithMobileVerification')]</value>
      <webElementGuid>3671dc4c-92ef-4561-a3c8-5f008e4f860d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a</value>
      <webElementGuid>06afccba-93f5-43e9-b8fc-4a646dfbff35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ap-account-fixup-phone-skip-link' and @href = 'https://www.amazon.com/ap/signin?openid.pape.max_auth_age=900&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;appActionToken=zTyBv5j2Bc7KqhT0bllFj2BGTySOcRIj3D&amp;pageId=usflex&amp;openid.pape.preferred_auth_policies=http%3A%2F%2Fschemas.openid.net%2Fpape%2Fpolicies%2F2007%2F06%2Fnone&amp;openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3Fref_%3Dnav_custrec_signin%26returnFromLogin%3D1&amp;openid.assoc_handle=usflex&amp;partialToken=PT%7C1%7C0I1P7oBYDg0N0YFk81K6qp8gGH8INH7Q436iAkfOIWgstUFVvAkg9zz3bdb1Mi3OBVQT06yNUHxe0NV6txZ25IQjZNKlsiBKuzrBlGvfGBz9zwLUeaemSzqnKVEiLiddkblNiyBy7wz+5jz93LQFd9I8EBZCnKoMrHYx1mjNR721CZYtSQyjSJ2v%2FbeIMneta5CJTlMty+wKWRZyl%2Fj2X8OI61l03L99UkqlBVdUzgGBdjNJe6OycAD+mEms3ZDSu2XiKr2jQT%2F6NE%2FzPAD2C0Wr%2F5IeKafvQwjBjOpuBCu5uAc51XWZsCV1TkHIsXz5yiD5aU9Kf8rcs1hAERO03A%3D%3D&amp;openid.mode=checkid_setup&amp;appAction=ACCOUNT_FIXUP_PHONE_ADD_COMPLETE&amp;ref_=ap_reachability_skip&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;authenticationPolicy=SinglefactorWithMobileVerification' and (text() = '
                  Not now
                ' or . = '
                  Not now
                ')]</value>
      <webElementGuid>62196f2f-9ed0-4993-a94f-9a8a38dcfead</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
