<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_nav-flyout-buffer-top</name>
   <tag></tag>
   <elementGuidId>2bdefbc9-387a-49c3-94f2-03dbefd2f9af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-flyout-accountList']/div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-flyout-accountList > div.nav-flyout-buffer-top</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9e6d9ed6-3d55-49f0-826e-82b243b43bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-flyout-buffer-top</value>
      <webElementGuid>31a9e28a-0edc-4962-8e2c-742a6e26e7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-flyout-accountList&quot;)/div[@class=&quot;nav-flyout-buffer-top&quot;]</value>
      <webElementGuid>c004e787-4884-4db0-9813-87633b31f214</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-flyout-accountList']/div[5]</value>
      <webElementGuid>b09e1777-8232-43e8-99e1-b3c85d9cea0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[5]</value>
      <webElementGuid>aadab29e-260b-4571-bc8d-a0477a59ef51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
